default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ledger_development
  url: <%= Rails.application.credentials.dev[:db_url] %>

test:
  <<: *default
  database: ledger_test
  url: <%= Rails.application.credentials.test[:db_url] %>

production:
  <<: *default
  url: <%= Rails.application.credentials.prod[:db_url] %>
